config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  mount RailsAdmin::Engine => '/kanrishapeizi', as: 'rails_admin'

  get  'admins/precheck_service', format: false
  get  'admins/orderbook_exec', format: false
  get  'admins/orderbook_trade2acnt', format: false
  get  'admins/orderbook_depth', format: false  
  get  'admins/orderbook_plot', format: false
  get  'admins/orderbook_total', format: false
  get  'admins/pricehist_exec', format: false
  get  'admins/pricehist_plot', format: false
  get  'admins/pricehist_total', format: false
  get  'admins/walletcheck_exec', format: false
  get  'admins/test_email_new', format: false
  post 'admins/test_email_create', format: false

  get  'admins/index_order_btc_ltc', format: false
  get  'admins/index_order_btc_mona', format: false
  get  'admins/index_order_btc_doge', format: false
  get  'admins/index_order_ltc_mona', format: false
  get  'admins/index_order_ltc_doge', format: false
  get  'admins/index_order_mona_doge', format: false

  resource :closed_orders, only: [:new, :create], format: false
  get  'closed_orders/delete_new', format: false
  post 'closed_orders/delete_check', format: false
  post 'closed_orders/delete_create', format: false

  resource :open_orders, only: [:new, :create], format: false

  get  'admins/book_make_control', format: false

  match '/:locale' => 'orders#btc_ltc', via: [ :get ], format: false

  scope "(:locale)", locale: /ja|en/ do 

    root 'orders#btc_ltc', format: false
 
    get  'orders/btc_ltc', format: false
    get  'orders/btc_mona', format: false
    get  'orders/btc_doge', format: false
    get  'orders/ltc_mona', format: false
    get  'orders/ltc_doge', format: false
    get  'orders/mona_doge', format: false
 
    get  'static_pages/explanation', format: false
    get  'static_pages/contact_new', format: false
    post 'static_pages/contact_create', format: false

    devise_scope :user do
      get  'users/edit', to: 'users/registrations#edit'
      get  'users/sign_up', to: 'users/registrations#new'
      get  'users/sign_in', to: 'users/sessions#new'
      post 'users', to: 'users/registrations#create'
    end
    devise_for :users, except: [ :destroy ] #どうもうまく消えてないようだ。

    get  'orders/index_btc_ltc', format: false
    get  'orders/index_btc_mona', format: false
    get  'orders/index_btc_doge', format: false
    get  'orders/index_ltc_mona', format: false
    get  'orders/index_ltc_doge', format: false
    get  'orders/index_mona_doge', format: false

    resources :orders, only: [:create, :show, :edit, :update], format: false

    get  'acnts/show', format: false

    get  'coinios/coinio_btc', format: false
    get  'coinios/coinio_ltc', format: false
    get  'coinios/coinio_mona', format: false
    get  'coinios/coinio_doge', format: false

    resources :coinios, only: [:create, :show], format: false

    get '*anything' => 'orders#btc_ltc'
  end

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  coin_a_id  :integer
#  coin_b_id  :integer
#  amt_a_org  :decimal(32, 8)   default(0.0), not null
#  amt_b_org  :decimal(32, 8)   default(0.0), not null
#  amt_a      :decimal(32, 8)   default(0.0), not null
#  amt_b      :decimal(32, 8)   default(0.0), not null
#  rate       :decimal(32, 10)  default(0.0), not null
#  buysell    :boolean
#  flag       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :coin_a, class_name: "Cointype"
  belongs_to :coin_b, class_name: "Cointype"
  has_many :trades

  enum flag: {open_new: 0, open_per: 2, noex_cncl: 5, exec_cncl: 7, noex_expr: 9, exec_expr: 11, exec_exec: 15,
              b_fnsh: 1, b_onee: 2, b_cncl: 4, b_expr: 8, b_exec: 12 }

  # あとで、b_fnsh: 1, b_onee: 2, b_cncl: 4, b_expr: 8, b_exec: 12
  # をとりのぞく必要がある（だろう）。なぜなら、つかう方法がない。

  scope :openor, -> { where(flag: [0, 2]) }

  scope :match_order_sell, -> (max) { where(buysell: true).where(flag: [0, 2])
                .where('rate <= ?', max).order('rate ASC, created_at ASC') } 
  scope :match_order_buy, -> (min) { where(buysell: false).where(flag: [0, 2])
                .where('rate >= ?', min).order('rate DESC, created_at ASC') } 
  scope :coins, -> (coin1, coin2) { where("(coin_a_id = ? AND coin_b_id = ?)",coin1, coin2) }
  # scope :coin2ways, -> (coin1, coin2) { where("(coin_a_id = ? AND coin_b_id = ?) OR (coin_a_id = ? AND coin_b_id = ?)",
  #        coin1, coin2, coin2, coin1) }
  scope :coin_rel, -> (rel) { where("(coin_a_id = ? AND coin_b_id = ?)",rel.coin_a, rel.coin_b) }

  validates :user_id, presence: true
  validates :coin_a_id, presence: true
  validates :coin_b_id, presence: true
  validates :rate, numericality: { greater_than: 0.0 } 
  validates :amt_a, numericality: { greater_than_or_equal_to: 0.0 }
  validates :amt_b, numericality: { greater_than_or_equal_to: 0.0 } 
  validates :amt_a_org, numericality: { greater_than: 0.0 }
  validates :amt_b_org, numericality: { greater_than: 0.0 } 
  validates :flag, presence:  true
  # validate :flag_with_zero_amount


  # check if inputted amounts are numeric or not on the order
  # check if inputted amounts are positive or not
  # 一部のvalidationだけをさせたいために、わざわさこのメソッドを定義している。
  def valid_prep?
    flag = true
    unless self.rate.is_a?(Numeric) then
      self.errors.add(:rate, I18n.t('errors.messages.not_a_number'))
      flag = false
    end
    unless self.amt_a.is_a?(Numeric) then 
      self.errors.add(:amt_a, I18n.t('errors.messages.not_a_number'))
      flag = false
    end
    return unless flag
    if self.rate <= 0.0 then
      self.errors.add(:rate, I18n.t('errors.messages.order.zero_or_negative'))
      flag = false
    end
    if self.amt_a_org <= 0.0 then 
      self.errors.add(:amt_a, I18n.t('errors.messages.order.zero_or_negative'))
      flag = false
    end
    return flag
  end

  # flag は文字列として処理されるため、ビット演算子「＆」でエラーが起こる
  # private
  #   def flag_with_zero_amount
  #     if (self.amt_a == 0.0 || self.amt_b == 0) then
  #       if (flag & 0b1) != 0b1 then
  #         self.errors.add(:flag, "flag with 0 amount(s) should be closed ones")
  #       end
  #     end
  #   end

end

# 0th bit  0: not finishted, 1: finished
# 1th bit  0: no execution, 1: 1 or more execution(s)
# 2nd, 3rd bit:  closing-status
#   01: expired
#   10: canceled
#   11: excecutsion
#
#   0000: 00: open_new     :no execution yet, open 
#   0100: 02: open_per     :pertially executed, open
#   1001: 09: noex_expr  :no execution, expired&closed 
#   1010: 05: noex_cncl  :no execution, canceled&closed
#   1101: 11: exec_expr  :execution(s), expired at last &closed
#   1110: 07: exec_cncl  :execution(s), cancled at last &closed
#   1111: 15: exec_exec  :execution(s), executed at last &closed
#
#   1000: 01: B_fnsh
#   0100: 02: B_onee
#   0010: 04: B_cncl
#   0001: 08: B_expr 
#   0011: 12: B_exec

app/controllers/orders_controller.rb
# require 'usrdaemons/settle_order'

class OrdersController < ApplicationController

  include CoinUtil

  before_action :authenticate_user!, only: [ :create, :show, :edit, :update,
     :index_btc_ltc,  :index_btc_mona, :index_btc_doge, 
     :index_ltc_mona, :index_ltc_doge, :index_mona_doge] 

  def btc_ltc
    common_new('BTC', 'LTC')
  end

  def btc_mona
    common_new('BTC', 'MONA')
  end

  def btc_doge
    common_new('BTC', 'DOGE')
  end

  def ltc_mona
    common_new('LTC', 'MONA')
  end

  def ltc_doge
    common_new('LTC', 'DOGE')
  end

  def mona_doge
    common_new('MONA', 'DOGE')
  end

  def create

    # 入力コラムが、レート、数量ともに２つづつあり、セキュリティー上問題がありそう。修正する必要あり。
 
    @order = Order.new(order_params)
    @coin_a = @order.coin_a
    @coin_b = @order.coin_b
    if params[:sell] then # sell
      @buysellinfo = "sell"
      buysell = true
      # @order.buysell = true
    elsif params[:buy] then # buy
      @buysellinfo = "buy"
      buysell = false
      # @order.buysell = false
    else
      # raise StandardError, 'neither buy nor sell !'
      # 起こらないはず。
      # もう少し良く考える必要があるだろう。
      @order.errors.add(:base, I18n.t('errors.messages.order.try_later'))    
      @lang_link = true
      render 'common_new'
      return
    end

    # エラーでrenderするための用意！
    common_new_set
    action_s = @coin_a.ticker.downcase + '_' + @coin_b.ticker.downcase
    @lang_link = false
    @japanese_path = url_for(locale: 'ja', controller: :orders, action: action_s, only_path: true)
    @english_path = url_for(locale: 'en', controller: :orders, action: action_s, only_path: true)

    # orderを作る
    amt = ( buysell ? @order.amt_a : @order.rate * @order.amt_a) 
    cr = CoinRelation.find_by(coin_a:  @order.coin_a, coin_b: @order.coin_b)
    order_create = OrderCreate.new(user: current_user, coin_relation: cr, 
      rate: @order.rate, buysell: buysell, amt: amt)

    # check order foramt is or not
    # check if acccount free balance is bigger than order amount
    unless order_create.check_order? then
      @order = order_create.get_order # エラーメッセージのために @order を取ってくる。
      @lang_link = true
      render 'common_new'
      return
    end

    begin
      order_create.save_new_order_with_acnt!
    rescue => e
      @order.errors.add(:base, I18n.t('errors.messages.order.try_later'))    
      @lang_link = true
      render 'common_new'
      return
    end

    flash[ :notice ] = I18n.t('order.order_submit')
    redirect_to @order    
  end

  def show
    @order = Order.find(params[:id])
    @coin_a = @order.coin_a
    @coin_b = @order.coin_b
    coina_s = @coin_a.ticker.downcase
    coinb_s = @coin_b.ticker.downcase
    action_s = coina_s + '_' + coinb_s
    @path = url_for(locale: I18n.locale, controller: :orders, action: action_s, only_path: true)
    @headinfo = "trade"
  end

  def index_btc_ltc
    common_index('BTC', 'LTC')
  end

  def index_btc_mona
    common_index('BTC', 'MONA')
  end

  def index_btc_doge
    common_index('BTC', 'DOGE')
  end

  def index_ltc_mona
    common_index('LTC', 'MONA')
  end

  def index_ltc_doge
    common_index('LTC', 'DOGE')
  end

  def index_mona_doge
    common_index('MONA', 'DOGE')
  end

  def edit
    begin
      @order = Order.find(params[:id])
    rescue => e  # データが存在しない時の処理
      logger.warn('Order controller edit: cannot get order data from DB')
      logger.warn('class:' + e.class.to_s)
      logger.warn('msg' + e.message)
      flash[ :alert ] = I18n.t('order.only_owner_can_see')
      redirect_to root_path and return
    end

   # 他人のオーダーを変更できないようにする。チェック！！
    if @order.user.id != current_user.id then
      flash[ :alert ] = I18n.t('order.only_owner_can_see')
      redirect_to root_path
    end

    @trades = @order.trades.non_diff.page(params[:page])
  end

  def update  # cancellation
    begin
      @order = Order.find(params[:id])
    rescue => e  # データが存在しない時の処理
      logger.warn('Order controller Update: cannot get order data from DB')
      logger.warn('class:' + e.class.to_s)
      logger.warn('msg:' + e.message)
      flash[ :alert ] = I18n.t('order.only_owner_can_see')
      redirect_to root_path and return
    end

   # 他人のオーダーを変更できないようにする。チェック！！
    if @order.user.id != current_user.id then
      flash[ :alert ] = I18n.t('order.only_owner_can_cancel')
      redirect_to root_path and return
    end

    # オーダーがOpenで無い場合
    if (( @order.flag != "open_new") && ( @order.flag != "open_per")) then 
      flash[ :alert ] = I18n.t('order.not_open')
      redirect_to root_path and return
    end

    order_cancel = OrderCancel.new( @order )
    unless order_cancel.prep_cancel?
      # TODO ただし、画面から操作すればここに来ないはず。
    end

    begin
      order_cancel.save_cancel!
    rescue => e
      flash[ :alert ] = I18n.t('errors.messages.order.try_later')
      # @order.errors.add(:base, I18n.t('errors.messages.order.try_later'))
      redirect_back_or(root_path)
      return
    end

    flash[ :notice ] = I18n.t('order.canceled')
    redirect_back_or(root_path)
  end

  private
    def common_new(coin1, coin2)
      @coin_a, @coin_b = coin_order(coin1, coin2)
      @order = Order.new(coin_a_id: @coin_a.id, coin_b_id: @coin_b.id)
      @buysellinfo = "buy"
      common_new_set
      store_location
      render 'common_new'      
    end

    def common_new_set
      @headinfo = "trade"
      @tabinfo = @coin_a.ticker + '-' + @coin_b.ticker
      @candleplot = "\'" + @tabinfo + '_candle' + "\'"
      @histplot = "\'" + @tabinfo + "_hist_" + I18n.locale.to_s + "\'"
      @step_min = CoinRelation.find_by(coin_a_id: @coin_a.id, coin_b_id: @coin_b.id).step_min
      if current_user then
        a = Acnt.find_by(user_id: current_user.id, cointype_id: @coin_a.id)
        b = Acnt.find_by(user_id: current_user.id, cointype_id: @coin_b.id)
        @coin_a_bal = a.balance
        @coin_a_freebal = a.balance - a.locked_bal
        @coin_b_bal = b.balance
        @coin_b_freebal = b.balance - b.locked_bal
        @op_orders = current_user.orders.openor.coins(@coin_a.id, @coin_b.id)
                    .order('created_at DESC', 'rate DESC').page(params[:page]).per(5)
      end
      @path12 = orders_btc_ltc_path
      @path13 = orders_btc_mona_path
      @path14 = orders_btc_doge_path
      @path23 = orders_ltc_mona_path
      @path24 = orders_ltc_doge_path
      @path34 = orders_mona_doge_path
    end

    def common_index(coin1, coin2)
      @coin_a, @coin_b = coin_order(coin1, coin2)
      @orders = current_user.orders.coins(@coin_a.id, @coin_b.id).order('created_at DESC', 'rate DESC').page(params[:page]) 
      @headinfo = "order_list"
      @tabinfo = @coin_a.ticker + '-' + @coin_b.ticker
      @path12 = orders_index_btc_ltc_path
      @path13 = orders_index_btc_mona_path
      @path14 = orders_index_btc_doge_path
      @path23 = orders_index_ltc_mona_path
      @path24 = orders_index_ltc_doge_path
      @path34 = orders_index_mona_doge_path
      store_location
      render 'common_index'
    end

    def order_params
      params.require(:order).permit(:coin_a_id, :coin_b_id, :rate, :amt_a)
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
  def order_flag(status)
  	case  status 
    when "open_new" then
  	  t('order.flag.open_new')
    when "open_per" then
  	  t('order.flag.open_per')
    when "noex_cncl" then
  	  t('order.flag.noex_cncl')
    when "exec_cncl" then
  	  t('order.flag.exec_cncl')
    when "noex_expr" then
  	  t('order.flag.noex_expr')
    when "exec_expr" then
  	  t('order.flag.exec_expr')  	  
    when "exec_exec" then
  	  t('order.flag.exec_exec')
    end
  end

  def order_buysell(buysell)
  	if buysell then
      t('order.sell')
  	else
      t('order.buy')
  	end
  end

  def trade_flag(status)
    case status
    when "tr_close" then
      t('trade.flag.tr_close')
    when "tr_cncl" then
      t('trade.flag.tr_cncl')
    when "tr_expr" then
      t('trade.flag.tr_expr')
    end
  end

end

app/views/orders/_order.html.erb
<tr>
    <td style="text-align:center;"><%= l(order.created_at, format: :short) %></td>
    <td style="text-align:center;"><%= order_buysell(order.buysell) %></td>   
    <td style="text-align:center;"><%= order.rate %></td>
    <td style="text-align:center;"><%= order.amt_a_org %></td>
    <td style="text-align:center;"><%= order.amt_a %></td>   
    <td style="text-align:center;"><%= order.amt_b_org %></td>
    <td style="text-align:center;"><%= order.amt_b %></td>
</tr>

app/views/orders/common_index.html.erb
<h1><%= t('order.order') %></h1>

<%= render 'layouts/coin2tab' %>

<div style="background:white;margin:0px 2px 20px;padding:10px;">
  <% if signed_in? && @orders.any? %>
    <table class="table table-bordered table-condensed" >
      <tr>
        <th style="text-align:center;"><%= t('order.order_date') %></th>
        <th style="text-align:center;"><%= @coin_a.ticker %><br /><%= t('order.sell_buy') %></th>
        <th style="text-align:center;"><%= t('order.rate') %><br /><%= @coin_a.ticker %> / <%= @coin_b.ticker %></th>
        <th style="text-align:center;"><%= t('order.order_amount') %> [<%= @coin_a.ticker %>] </th>
        <th style="text-align:center;"><%= t('order.remaining_amount') %> [<%= @coin_a.ticker %>] </th>
        <th style="text-align:center;"><%= t('order.order_amount') %> [<%= @coin_b.ticker %>] </th>
        <th style="text-align:center;"><%= t('order.remaining_amount') %> [<%= @coin_b.ticker %>] </th>
        <th style="text-align:center;"><%= t('order.status') %></th>
        <th style="text-align:center;"><%= t('order.ops') %></th>
      </tr>
      <% @orders.each do | order | %>
        <tr>  
           <td style="text-align:center;"><%= l(order.created_at, format: :short) %></td>
           <td style="text-align:center;"><%= order_buysell(order.buysell) %></td>   
           <td style="text-align:center;"><%= order.rate %></td>
           <td style="text-align:center;"><%= order.amt_a_org %></td>
           <td style="text-align:center;"><%= order.amt_a %></td>   
           <td style="text-align:center;"><%= order.amt_b_org %></td>
           <td style="text-align:center;"><%= order.amt_b %></td>   
           <td style="text-align:center;"><%= order_flag(order.flag) %></td>
           <td style="text-align:center;">
               <%= link_to t('order.detail'), edit_order_path(order) %></td>           
        </tr>
      <% end %>      
    </table>
    <%= page_entries_info(@orders) %>
    <br />
    <%= paginate @orders %>
  <% else %>
    <p><%= t('order.no_order') %></p>  
  <% end %>
</div>

app/views/orders/edit.html.erb
<h2> <%= t('order.order_detail') %></h2>
<div style="padding:10px;background:white;margin:10px 10px 15px;">
  <table class="table table-bordered table-condensed" >
    <tr>
      <th style="text-align:center;"><%= t('order.order_date') %></th>
      <th style="text-align:center;"><%= @order.coin_a.ticker %> <%= t('order.sell_buy') %></th>
      <th style="text-align:center;"><%= t('order.rate') %> <%= @order.coin_a.ticker %> / <%= @order.coin_b.ticker %></th>
      <th style="text-align:center;"><%= t('order.order_amount') %> [<%= @order.coin_a.ticker %>] </th>
      <th style="text-align:center;"><%= t('order.remaining_amount') %> [<%= @order.coin_a.ticker %>] </th>
      <th style="text-align:center;"><%= t('order.order_amount') %> [<%= @order.coin_b.ticker %>] </th>
      <th style="text-align:center;"><%= t('order.remaining_amount') %> [<%= @order.coin_b.ticker %>] </th>
      <th style="text-align:center;"><%= t('order.status') %></th>
    </tr>
    <tr>  
     <td style="text-align:center;"><%= l(@order.created_at, format: :short) %></td>
     <td style="text-align:center;"><%= order_buysell(@order.buysell) %></td>   
     <td style="text-align:center;"><%= @order.rate %></td>
     <td style="text-align:center;"><%= @order.amt_a_org %></td>
     <td style="text-align:center;"><%= @order.amt_a %></td>   
     <td style="text-align:center;"><%= @order.amt_b_org %></td>
     <td style="text-align:center;"><%= @order.amt_b %></td>   
     <td style="text-align:center;"><%= order_flag(@order.flag) %></td>
    </tr>
  </table>

  <% if @trades.any? %>
    <br />
    <h4><%= t('trade.closed_trade', count: @trades.count) %></h4>
    <table class="table table-bordered table-condensed" >
      <tr>
        <th style="text-align:center;"><%= t('trade.settle_date') %></th>
        <th style="text-align:center;"><%= t('trade.status') %></th>
        <th style="text-align:center;"><%= t('trade.amount') %> [<%= @order.coin_a.ticker %>]</th>
        <th style="text-align:center;"><%= t('trade.amount') %> [<%= @order.coin_b.ticker %>]</th>
        <th style="text-align:center;"><%= t('trade.fee') %> [
          <% if @order.buysell then %>
            <%= @order.coin_b.ticker %>
          <% else %>
            <%= @order.coin_a.ticker %>
          <% end %>        
          ]</th>
      </tr>
      <% @trades.each do | tr | %>
        <tr>  
           <td style="text-align:center;"><%= l(tr.updated_at, format: :short) %></td>
           <td style="text-align:center;"><%= trade_flag(tr.flag) %></td>   
           <td style="text-align:center;"><%= tr.amt_a %></td>   
           <td style="text-align:center;"><%= tr.amt_b %></td>   
           <td style="text-align:center;"><%= tr.fee %></td>
        </tr>
      <% end %>      
    </table>
    <%= page_entries_info(@trades) %>
    <br />
    <%= paginate @trades %>
  <% else %>
    <p><%= t('order.order_open_no_exec') %><p>
  <% end %>

  <% if @order.flag == "open_new" || @order.flag == "open_per" then %>
    <br />
    <h2><%= t('order.cancel_order') %></h2>
    <p><%= t('order.if_cancel_locked_released') %></p> 
    <% if @order.buysell then %>
      <p>  <%= @order.amt_a %>[<%= @order.coin_a.ticker %>]</p>
    <% else %>
      <p>  <%= @order.amt_b %>[<%= @order.coin_b.ticker %>]</p>
    <% end %>
    <%= form_for(@order, { action: :update } ) do | order | %>
      <%= order.submit t('order.cancel_button'), data: { confirm: t('order.confirm_cancel'), commit: t('order.commit_cancel'), cancel: t('order.cancel_cancel') }, title: t('order.confirm_title'), class: "btn btn-large btn-primary" %>
    <% end %>
  <% end %> 
</div>

app/views/orders/index_form.html.erb
<h2><%= t('order.order') %></h2>

<%= render 'layouts/coin2tab' %>

<div style="background:white;margin:0px 2px 20px;padding:10px;">
  <% if signed_in? && @orders.any? %>
    <table class="table table-bordered table-condensed" >
      <tr>
        <th style="text-align:center;"><%= t('order.order_date') %></th>
        <th style="text-align:center;"><%= @coin_a.ticker %><br /><%= t('order.sell_buy') %></th>
        <th style="text-align:center;"><%= t('order.rate') %><br /><%= @coin_a.ticker %> / <%= @coin_b.ticker %></th>
        <th style="text-align:center;"><%= t('order.order_amount') %> [<%= @coin_a.ticker %>] </th>
        <th style="text-align:center;"><%= t('order.remaining_amount') %> [<%= @coin_a.ticker %>] </th>
        <th style="text-align:center;"><%= t('order.order_amount') %> [<%= @coin_b.ticker %>] </th>
        <th style="text-align:center;"><%= t('order.remaining_amount') %> [<%= @coin_b.ticker %>] </th>
        <th style="text-align:center;"><%= t('order.status') %></th>
        <th style="text-align:center;"><%= t('order.ops') %></th>
      </tr>
      <% @orders.each do | order | %>
        <tr>  
           <td style="text-align:center;"><%= l(order.created_at, format: :short) %></td>
           <td style="text-align:center;"><%= order_buysell(order.buysell) %></td>   
           <td style="text-align:center;"><%= order.rate %></td>
           <td style="text-align:center;"><%= order.amt_a_org %></td>
           <td style="text-align:center;"><%= order.amt_a %></td>   
           <td style="text-align:center;"><%= order.amt_b_org %></td>
           <td style="text-align:center;"><%= order.amt_b %></td>   
           <td style="text-align:center;"><%= order_flag(order.flag) %></td>
           <td style="text-align:center;">
               <%= link_to t('order.detail'), edit_order_path(order) %></td>           
        </tr>
      <% end %>      
    </table>
    <%= page_entries_info(@orders) %>
    <br />
    <%= paginate @orders %>
  <% else %>
    <p><%= t('order.no_order') %></p>  
  <% end %>
</div>

app/views/orders/show.html.erb
<h2> <%= t('order.order_detail') %></h2>
<div style="padding:10px;background:white;margin:10px 10px 15px;">
  <table class="table table-bordered table-condensed" >
    <tr>
      <th style="text-align:center;"><%= t('order.order_date') %></th>
      <th style="text-align:center;"><%= @coin_a.ticker %> <%= t('order.sell_buy') %></th>
      <th style="text-align:center;"><%= t('order.rate') %> <%= @coin_a.ticker %> / <%= @coin_b.ticker %></th>
      <th style="text-align:center;"><%= t('order.order_amount') %> [<%= @coin_a.ticker %>] </th>
      <th style="text-align:center;"><%= t('order.remaining_amount') %> [<%= @coin_a.ticker %>] </th>
      <th style="text-align:center;"><%= t('order.order_amount') %> [<%= @coin_b.ticker %>] </th>
      <th style="text-align:center;"><%= t('order.remaining_amount') %> [<%= @coin_b.ticker %>] </th>
      <th style="text-align:center;"><%= t('order.status') %></th>
    </tr>
    <tr>  
     <td style="text-align:center;"><%= l(@order.created_at, format: :short) %></td>
     <td style="text-align:center;"><%= order_buysell(@order.buysell) %></td>   
     <td style="text-align:center;"><%= @order.rate %></td>
     <td style="text-align:center;"><%= @order.amt_a_org %></td>
     <td style="text-align:center;"><%= @order.amt_a %></td>   
     <td style="text-align:center;"><%= @order.amt_b_org %></td>
     <td style="text-align:center;"><%= @order.amt_b %></td>   
     <td style="text-align:center;"><%= order_flag(@order.flag) %></td>
    </tr>
  </table>
  <%= link_to t('order.back'), @path %>  
</div>