config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  mount RailsAdmin::Engine => '/kanrishapeizi', as: 'rails_admin'

  get  'admins/precheck_service', format: false
  get  'admins/orderbook_exec', format: false
  get  'admins/orderbook_trade2acnt', format: false
  get  'admins/orderbook_depth', format: false  
  get  'admins/orderbook_plot', format: false
  get  'admins/orderbook_total', format: false
  get  'admins/pricehist_exec', format: false
  get  'admins/pricehist_plot', format: false
  get  'admins/pricehist_total', format: false
  get  'admins/walletcheck_exec', format: false
  get  'admins/test_email_new', format: false
  post 'admins/test_email_create', format: false

  get  'admins/index_order_btc_ltc', format: false
  get  'admins/index_order_btc_mona', format: false
  get  'admins/index_order_btc_doge', format: false
  get  'admins/index_order_ltc_mona', format: false
  get  'admins/index_order_ltc_doge', format: false
  get  'admins/index_order_mona_doge', format: false

  resource :closed_orders, only: [:new, :create], format: false
  get  'closed_orders/delete_new', format: false
  post 'closed_orders/delete_check', format: false
  post 'closed_orders/delete_create', format: false

  resource :open_orders, only: [:new, :create], format: false

  get  'admins/book_make_control', format: false

  match '/:locale' => 'orders#btc_ltc', via: [ :get ], format: false

  scope "(:locale)", locale: /ja|en/ do 

    root 'orders#btc_ltc', format: false
 
    get  'orders/btc_ltc', format: false
    get  'orders/btc_mona', format: false
    get  'orders/btc_doge', format: false
    get  'orders/ltc_mona', format: false
    get  'orders/ltc_doge', format: false
    get  'orders/mona_doge', format: false
 
    get  'static_pages/explanation', format: false
    get  'static_pages/contact_new', format: false
    post 'static_pages/contact_create', format: false

    devise_scope :user do
      get  'users/edit', to: 'users/registrations#edit'
      get  'users/sign_up', to: 'users/registrations#new'
      get  'users/sign_in', to: 'users/sessions#new'
      post 'users', to: 'users/registrations#create'
    end
    devise_for :users, except: [ :destroy ] #どうもうまく消えてないようだ。

    get  'orders/index_btc_ltc', format: false
    get  'orders/index_btc_mona', format: false
    get  'orders/index_btc_doge', format: false
    get  'orders/index_ltc_mona', format: false
    get  'orders/index_ltc_doge', format: false
    get  'orders/index_mona_doge', format: false

    resources :orders, only: [:create, :show, :edit, :update], format: false

    get  'acnts/show', format: false

    get  'coinios/coinio_btc', format: false
    get  'coinios/coinio_ltc', format: false
    get  'coinios/coinio_mona', format: false
    get  'coinios/coinio_doge', format: false

    resources :coinios, only: [:create, :show], format: false

    get '*anything' => 'orders#btc_ltc'
  end

end

app/views/layouts/_coin2tab.html.erb
<div class="contents-tabs">
	<ul class="nav nav-tabs">
    <li class="tab-plane <% if @tabinfo == "BTC-LTC" then concat 'active' end %>" style="width:16.6%;" >
      <%= link_to "BTC/LTC", @path12 %>
    </li>
    <li class="tab-plane <% if @tabinfo == "BTC-MONA" then concat 'active' end %>" style="width:16.6%;" >
      <%= link_to "BTC/MONA", @path13 %>
    </li>
    <li class="tab-plane <% if @tabinfo == "BTC-DOGE" then concat 'active' end %>" style="width:16.6%;" >
      <%= link_to "BTC/DOGE", @path14 %>
    </li>    
    <li class="tab-plane <% if @tabinfo == "LTC-MONA" then concat 'active' end %>" style="width:16.6%;" >
      <%= link_to "LTC/MONA", @path23 %>
    </li>
    <li class="tab-plane <% if @tabinfo == "LTC-DOGE" then concat 'active' end %>" style="width:16.6%;" >
      <%= link_to "LTC/DOGE", @path24 %>
    </li>
    <li class="tab-plane <% if @tabinfo == "MONA-DOGE" then concat 'active' end %>" style="width:17%;" >
      <%= link_to "MONA/DOGE", @path34 %>
    </li>
	</ul>
</div>

app/views/layouts/_cointab.html.erb
<div class="contents-tabs">
	<ul class="nav nav-tabs">
  	<li class="tab-plane <% if @tabinfo == "BTC" then concat 'active' end %>" style="width:25%;" >
      <%= link_to "BTC", @path1 %>
    </li>
    <li class="tab-plane <% if @tabinfo == "LTC" then concat 'active' end %>" style="width:25%;" >
      <%= link_to "LTC", @path2 %>
    </li>
    <li class="tab-plane <% if @tabinfo == "MONA" then concat 'active' end %>" style="width:25%;" >
      <%= link_to "MONA", @path3 %>
    </li>
    <li class="tab-plane <% if @tabinfo == "DOGE" then concat 'active' end %>" style="width:25%;" >
      <%= link_to "DOGE", @path4 %>
    </li>
	</ul>
</div>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= t('errors.messages.contain_error', count: object.errors.count) %>
    </h2>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>

  <div class="wrapper">
    <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>
    <%= link_to image_tag('bitchange_logo.png', height: 33, width: 78, alt: 'BitChange'), Rails.application.secrets.host_url %>
    <span>&nbsp;<%= t('header.topline') %></span> 
    <span style="position:relative;float:right;">
      <% if signed_in? %>
        <%= current_user.email %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <% end %>
      <% if @lang_link %>
        <%= link_to_if params[:locale].present?, '日本語',  
          @japanese_path %>
        <%= link_to_if params[:locale] != 'en',  'English',  
          @english_path %>
          &nbsp;&nbsp;&nbsp;&nbsp; 
      <% else %>
        <%= link_to_if params[:locale].present?, '日本語',  
          url_for(controller: controller.controller_name, 
          action: controller.action_name, locale: '') %>
        <%= link_to_if params[:locale] != 'en',  'English',  
          url_for(controller: controller.controller_name, 
          action: controller.action_name, locale: 'en') %>
          &nbsp;&nbsp;&nbsp;&nbsp; 
      <% end %>
    </span>
  </div>

  <nav class="navbar navbar-default">
    <div class="container">
      <ul class="nav navbar-nav navbar-left">
        <li <% if @headinfo == "trade" then concat raw("class='active'") end %> >
          <%= link_to t('header.trade'), orders_btc_ltc_path %></li>
        <% if signed_in? %>
          <li <% if @headinfo == "order_list" then concat raw("class='active'") end %> >
            <%= link_to t('header.order_list'), orders_index_btc_ltc_path %></li>     
          <li <% if @headinfo == "transferIO" then concat raw("class='active'") end %> >
            <%= link_to t('header.transferIO'), coinios_coinio_btc_path %></li>
          <li <% if @headinfo == "balance" then concat raw("class='active'") end %> >
            <%= link_to t('header.balance'), acnts_show_path %></li>            
        <% end %>
        <li <% if @headinfo == "explanation" then concat raw("class='active'") end %> >
          <%= link_to t('header.explanation'), static_pages_explanation_path %></li>
        <li <% if @headinfo == "contact" then concat raw("class='active'") end %> >
          <%= link_to t('header.contact'), static_pages_contact_new_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li <% if @headinfo == "account" then concat raw("class='active'") end %> >
            <%= link_to t('header.account'), edit_user_registration_path %></li>
          <li><%= link_to t('header.logout'), destroy_user_session_path, method: "delete" %></li>
        <% else %>
          <li <% if @headinfo == "signup" then concat raw("class='active'") end %> >
            <%= link_to t('header.signup'), new_user_registration_path %></li>
          <li <% if @headinfo == "login" then concat raw("class='active'") end %> >
            <%= link_to t('header.login'), new_user_session_path %></li>
        <% end %>
      </ul>
    <div>
  </nav>

  <% if signed_in? && current_user.admin? then %>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navber-header">
          <h4 class="navber-text" style="display:inline">Admin menu</h4>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "precheck", admins_precheck_service_path %></li>            
            <li><%= link_to "rails_admin", rails_admin_path %></li>            
            <li><%= link_to "orders_list", admins_index_order_btc_mona_path %></li>
            <li><%= link_to "orders_exec", admins_orderbook_exec_path %></li>
            <li><%= link_to "orders_2acnt", admins_orderbook_trade2acnt_path %></li>
            <li><%= link_to "orders_depth", admins_orderbook_depth_path %></li>
            <li><%= link_to "orders_plots", admins_orderbook_plot_path %></li>
            <li><%= link_to "orders_total", admins_orderbook_total_path %></li>
            <li><%= link_to "prhist_exec", admins_pricehist_exec_path %></li>
            <li><%= link_to "prhist_plot", admins_pricehist_plot_path %></li>
            <li><%= link_to "prhist_total", admins_pricehist_total_path %></li>
            <li><%= link_to "wallet_exec", admins_walletcheck_exec_path %></li>
            <li><%= link_to "test_email", admins_test_email_new_path %></li>
            <li><%= link_to "Create_candle", new_closed_orders_path %></li>
            <li><%= link_to "delete_candle", closed_orders_delete_new_path %></li>
            <li><%= link_to "Create_multi-Orders", new_open_orders_path %></li>
            <li><%= link_to "BookMake-control", admins_book_make_control_path %></li>
          </ul>
        </div>
      </div>
    </nav>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

 <title><%= full_seo('title', yield( :cont )) %></title>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <script language="javascript" type="text/javascript" src="excanvas.js"></script>
  <![endif]-->

<%= favicon_link_tag 'favicon.ico' %>

<meta name="description" content="<%= full_seo('desc', yield( :cont )) %>">
<meta name="keywords" content="<%= full_seo('keywords', yield( :cont )) %>">

</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container" style="background:#E9E9E9">

    <% if alert %>
      <div class="alert alert-alert alert-dismissable" style="border:solid 1px #000">
        <button class="close" data-dismiss="alert" aria-hidden="true">&times:</button>
        <%= alert %>
      </div>
    <% end %>
    <% if notice %>
      <div class="alert alert-notice alert-dismissable" style="border:solid 1px #000">
        <button class="close" data-dismiss="alert" aria-hidden="true">&times:</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>

  </div>

  <div class="footer" >
    <div class="container">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </div>

</body>
</html>